### ISSUE TITLE
Understanding a code segment?

### ISSUE THREAD

**Issue by K-M-Ibrahim-Khalilullah** [hocop/Better_color_detection_for_OpenCV#1]
@hocop 
Thank you very much for your excellent ideas.
I have a question about about a code segment:
```
if dir_i in range(1,4):
				vector[dir_i-1] *= -1
			if dir_i == 4:
				vector = np.array([1.0,0.0,0.0])
			if dir_i == 5:
				vector = np.array([0.0,1.0,0.0])
			if dir_i == 6:
				vector = np.array([0.0,0.0,1.0])
```
What is dir_i? How you select the range(1,4)? 
Thanks again for your work

**Comment by hocop** [comment]
Hi Ibrahim!
This was like a lifetime ago... I will try to remember.
`dir_i` is an index of one of six directions in space. And `divide(s, dir_i)` tries to divide set into two subsets along the specified direction.
6 directions are x, y, z, and also 3 diagonals.
So, `dir_i in range(1,4)` means one of the diagonals of the box.
